# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alteridem Consulting
author: Rob Prouse
email: rob@prouse.org
description: >- # this means to ignore newlines until "baseurl:"
  Rob Prouse open source developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
highlighter: rouge
show_excerpts: false
paginate: 5

twitter_username: rprouse
github_username:  rprouse
linkedin_username: robprouse

# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
date_format: "%b %-d, %Y"

exclude: [".gitignore", ".editorconfig", "CNAME", "README.md", "Gemfile"]

header_pages:
  - about.md
  - privacy.md

feed:
  excerpt_only: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed       # https://github.com/jekyll/jekyll-feed
  - jekyll-seo-tag    # https://github.com/jekyll/jekyll-seo-tag
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

production_url: "https://alteridem.net"
#rss_path: /rss.xml
#atom_path: /atom.xml
host: 0.0.0.0
